BEGIN;

CREATE TABLE IF NOT EXISTS expert_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    expert_group_id INTEGER NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    avg_rating DECIMAL NOT NULL DEFAULT 0,
    max_tickets INTEGER NOT NULL,
    CONSTRAINT fk_users_expert_group
        FOREIGN KEY (expert_group_id) REFERENCES expert_groups (id),
    CONSTRAINT chk_users_max_tickets CHECK (max_tickets >= 0)
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id VARCHAR(64) NOT NULL UNIQUE,
    priority INTEGER NOT NULL,
    morda_type INTEGER NOT NULL,
    closed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id INTEGER NOT NULL,
    status INTEGER NOT NULL,
    return_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_tickets_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_tickets_return_count CHECK (return_count >= 0)
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    type INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    storage_key VARCHAR(64) NOT NULL UNIQUE,
    safe_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    original_size_bytes BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT chk_attachments_sizes
        CHECK (original_size_bytes >= 0 AND size_bytes >= 0),
    CONSTRAINT chk_attachments_dimensions
        CHECK (width > 0 AND height > 0)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    rating INTEGER NOT NULL,
    CONSTRAINT fk_reviews_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS tickets_workers (
    worker_id INTEGER NOT NULL,
    ticket_id INTEGER NOT NULL,
    is_responsible BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actual BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (worker_id, ticket_id),
    CONSTRAINT fk_tickets_workers_worker
        FOREIGN KEY (worker_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_workers_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE TABLE IF NOT EXISTS cats_expert_groups (
    group_id INTEGER NOT NULL,
    cat_id INTEGER NOT NULL,
    PRIMARY KEY (group_id, cat_id),
    CONSTRAINT fk_cats_expert_groups_group
        FOREIGN KEY (group_id) REFERENCES expert_groups (id),
    CONSTRAINT fk_cats_expert_groups_category
        FOREIGN KEY (cat_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT fk_questions_category
        FOREIGN KEY (cat_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id) REFERENCES questions (id),
    CONSTRAINT uq_answers_id_question UNIQUE (id, question_id)
);

CREATE TABLE IF NOT EXISTS "QA" (
    question_id INTEGER NOT NULL,
    answer_id INTEGER NOT NULL,
    ticket_id INTEGER NOT NULL,
    PRIMARY KEY (question_id, answer_id, ticket_id),
    CONSTRAINT fk_qa_question
        FOREIGN KEY (question_id) REFERENCES questions (id),
    CONSTRAINT fk_qa_answer
        FOREIGN KEY (answer_id, question_id) REFERENCES answers (id, question_id),
    CONSTRAINT fk_qa_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE TABLE IF NOT EXISTS crisis_contact (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact TEXT NOT NULL,
    ticket_id INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crisis_contact_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE INDEX IF NOT EXISTS idx_tickets_category_id ON tickets (category_id);
CREATE INDEX IF NOT EXISTS idx_tickets_queue ON tickets (status, priority, created_at, id);
CREATE INDEX IF NOT EXISTS idx_users_expert_group_id ON users (expert_group_id);
CREATE INDEX IF NOT EXISTS idx_messages_ticket_created ON messages (ticket_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_attachments_ticket_id ON attachments (ticket_id);
CREATE INDEX IF NOT EXISTS idx_reviews_ticket_id ON reviews (ticket_id);
CREATE INDEX IF NOT EXISTS idx_tickets_workers_ticket_actual
    ON tickets_workers (ticket_id, actual);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tickets_workers_responsible
    ON tickets_workers (ticket_id) WHERE is_responsible AND actual;
CREATE INDEX IF NOT EXISTS idx_cats_expert_groups_cat_id ON cats_expert_groups (cat_id);
CREATE INDEX IF NOT EXISTS idx_questions_cat_id ON questions (cat_id);
CREATE INDEX IF NOT EXISTS idx_answers_question_id ON answers (question_id);
CREATE INDEX IF NOT EXISTS idx_qa_ticket_id ON "QA" (ticket_id);

COMMIT;
