BEGIN;

-- Values outside the agreed MVP enums are normalized before constraints are
-- installed so an existing development database can be migrated safely.
UPDATE tickets SET priority = 1 WHERE priority NOT IN (1, 2);
UPDATE tickets SET morda_type = 1 WHERE morda_type NOT IN (1, 2, 3);

ALTER TABLE tickets
    ADD CONSTRAINT chk_tickets_priority
        CHECK (priority BETWEEN 1 AND 2),
    ADD CONSTRAINT chk_tickets_morda_type
        CHECK (morda_type BETWEEN 1 AND 3);

ALTER TABLE messages
    DROP CONSTRAINT chk_messages_type,
    ADD CONSTRAINT chk_messages_type
        CHECK (type BETWEEN 1 AND 6);

-- ticket_events is an audit trail. It keeps operator actions and assignment
-- history even though tickets_workers stores only the current relationship.
CREATE TABLE IF NOT EXISTS ticket_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL,
    actor_user_id INTEGER,
    event_type VARCHAR(40) NOT NULL,
    from_status INTEGER,
    to_status INTEGER,
    from_worker_id INTEGER,
    to_worker_id INTEGER,
    reason_code VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_events_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_ticket_events_actor
        FOREIGN KEY (actor_user_id) REFERENCES users (id),
    CONSTRAINT fk_ticket_events_from_worker
        FOREIGN KEY (from_worker_id) REFERENCES users (id),
    CONSTRAINT fk_ticket_events_to_worker
        FOREIGN KEY (to_worker_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_ticket_events_ticket_created
    ON ticket_events (ticket_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_ticket_events_actor_created
    ON ticket_events (actor_user_id, created_at, id);

COMMIT;
